### ISSUE TITLE
"transferred from" links aren't always fully qualified

### ISSUE THREAD

**Issue by Fryguy** [juliancheal/code-extractor#5]
I think this may actually be more of a verification check that the upstream_name parameter is fully qualified, since that is what's used to generate the transferred from link.  Fully qualified in this case means that it includes both the org and repo (e.g. ManageIQ/manageiq-gems-pending) as opposed to just the repo (e.g. manageiq-gems-pending)

cc @carbonin

**Comment by juliancheal** [comment]
Thanks @Fryguy.

**Comment by Fryguy** [comment]
I added some documentation about the upstream_name parameter in #6 , so perhaps this can be closed as documented once that's merged.
